"""Updated All tables

Revision ID: 1ea0e3aa7ae7
Revises: a7e4f735263c
Create Date: 2023-11-20 13:24:13.472802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ea0e3aa7ae7'
down_revision = 'a7e4f735263c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartTime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('EndTime', sa.DateTime(), nullable=False))
        batch_op.drop_column('Time_Range')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.drop_column('role')

    with op.batch_alter_table('vaccination_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DoseNumber', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_schedule', schema=None) as batch_op:
        batch_op.drop_column('DoseNumber')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Time_Range', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('EndTime')
        batch_op.drop_column('StartTime')

    op.drop_table('role')
    # ### end Alembic commands ###
