"""Creating all Tables

Revision ID: 7e7a47d7658d
Revises: 
Create Date: 2023-11-03 03:23:09.946621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7a47d7658d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse',
    sa.Column('EmployeeID', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=80), nullable=False),
    sa.Column('Middle_Initial', sa.String(length=1), nullable=True),
    sa.Column('Last_Name', sa.String(length=80), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Phone_Number', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_table('patient',
    sa.Column('SSN', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(length=80), nullable=False),
    sa.Column('Middle_Initial', sa.String(length=1), nullable=True),
    sa.Column('Last_Name', sa.String(length=80), nullable=False),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Gender', sa.String(length=10), nullable=True),
    sa.Column('Race', sa.String(length=30), nullable=True),
    sa.Column('Occupation_Class', sa.String(length=50), nullable=True),
    sa.Column('Medical_History_Description', sa.String(length=255), nullable=True),
    sa.Column('Phone_Number', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('SSN')
    )
    op.create_table('time_slot',
    sa.Column('SlotID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Time_Range', sa.String(length=20), nullable=True),
    sa.Column('Maximum_Capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('SlotID')
    )
    op.create_table('vaccine',
    sa.Column('VaccineID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('Company', sa.String(length=120), nullable=True),
    sa.Column('Number_of_Doses', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Availability', sa.Integer(), nullable=True),
    sa.Column('OnHold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('VaccineID')
    )
    op.create_table('nurse_schedule',
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('NurseEmployeeID', sa.Integer(), nullable=True),
    sa.Column('TimeSlotID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NurseEmployeeID'], ['nurse.EmployeeID'], ),
    sa.ForeignKeyConstraint(['TimeSlotID'], ['time_slot.SlotID'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    op.create_table('vaccination_record',
    sa.Column('RecordID', sa.Integer(), nullable=False),
    sa.Column('PatientSSN', sa.Integer(), nullable=True),
    sa.Column('NurseEmployeeID', sa.Integer(), nullable=True),
    sa.Column('VaccineID', sa.Integer(), nullable=True),
    sa.Column('TimeSlotID', sa.Integer(), nullable=True),
    sa.Column('DoseNumber', sa.Integer(), nullable=False),
    sa.Column('Vaccination_Time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['NurseEmployeeID'], ['nurse.EmployeeID'], ),
    sa.ForeignKeyConstraint(['PatientSSN'], ['patient.SSN'], ),
    sa.ForeignKeyConstraint(['TimeSlotID'], ['time_slot.SlotID'], ),
    sa.ForeignKeyConstraint(['VaccineID'], ['vaccine.VaccineID'], ),
    sa.PrimaryKeyConstraint('RecordID')
    )
    op.create_table('vaccination_schedule',
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('PatientSSN', sa.Integer(), nullable=True),
    sa.Column('VaccineID', sa.Integer(), nullable=True),
    sa.Column('TimeSlotID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.Enum('Scheduled', 'Completed', 'Canceled'), nullable=True),
    sa.ForeignKeyConstraint(['PatientSSN'], ['patient.SSN'], ),
    sa.ForeignKeyConstraint(['TimeSlotID'], ['time_slot.SlotID'], ),
    sa.ForeignKeyConstraint(['VaccineID'], ['vaccine.VaccineID'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination_schedule')
    op.drop_table('vaccination_record')
    op.drop_table('nurse_schedule')
    op.drop_table('vaccine')
    op.drop_table('time_slot')
    op.drop_table('patient')
    op.drop_table('nurse')
    # ### end Alembic commands ###
