"""Added time

Revision ID: 80d20dc3c5bb
Revises: ef3763327adb
Create Date: 2023-11-22 22:35:05.884525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80d20dc3c5bb'
down_revision = 'ef3763327adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.alter_column('StartTime',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('EndTime',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)

    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.alter_column('Vaccination_Time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.alter_column('Vaccination_Time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.alter_column('EndTime',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('StartTime',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
