"""Datetime

Revision ID: f8a53c8bcf5a
Revises: 80d20dc3c5bb
Create Date: 2023-11-23 23:30:29.348074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8a53c8bcf5a'
down_revision = '80d20dc3c5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.alter_column('Vaccination_Time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_record', schema=None) as batch_op:
        batch_op.alter_column('Vaccination_Time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
