"""Added timeslot deatils try1

Revision ID: fc9b76e2dbda
Revises: 1ea0e3aa7ae7
Create Date: 2023-11-22 20:30:48.922111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc9b76e2dbda'
down_revision = '1ea0e3aa7ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurseSchedule',
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('NurseEmployeeID', sa.Integer(), nullable=True),
    sa.Column('TimeSlotID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NurseEmployeeID'], ['nurse.EmployeeID'], ),
    sa.ForeignKeyConstraint(['TimeSlotID'], ['time_slot.SlotID'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    op.drop_table('nurse_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse_schedule',
    sa.Column('ScheduleID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('NurseEmployeeID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('TimeSlotID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['NurseEmployeeID'], ['nurse.EmployeeID'], name='nurse_schedule_ibfk_1'),
    sa.ForeignKeyConstraint(['TimeSlotID'], ['time_slot.SlotID'], name='nurse_schedule_ibfk_2'),
    sa.PrimaryKeyConstraint('ScheduleID'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('nurseSchedule')
    # ### end Alembic commands ###
